"""Initial migration

Revision ID: e3cce039db7d
Revises: 
Create Date: 2026-06-17 18:08:55.057498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3cce039db7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('subscription_type', sa.String(length=50), server_default='free', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('origin_name', sa.String(length=255), nullable=False),
    sa.Column('destination_name', sa.String(length=255), nullable=False),
    sa.Column('train_dep_code', sa.String(length=50), nullable=True),
    sa.Column('train_arv_code', sa.String(length=50), nullable=True),
    sa.Column('bus_dep_id', sa.String(length=50), nullable=True),
    sa.Column('bus_arv_id', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('transport_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscriptions_active_date', 'subscriptions', ['is_active', 'date'], unique=False)
    op.create_table('subscription_states',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('last_state', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_states')
    op.drop_index('idx_subscriptions_active_date', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
